# name: morpheus
# description: "A new Flutter project."
# publish_to: 'none' # Remove esta linha se desejares publicar no pub.dev

# version: 1.0.0+1

# environment:
#   sdk: ^3.9.2

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/moon_logo.png
#     - assets/stars_bg.jpg
# name: morpheus
# description: "A new Flutter project."
# publish_to: 'none' # Remove esta linha se desejares publicar no pub.dev

# version: 1.0.0+1

# environment:
#   sdk: '>=3.9.2 <4.0.0' # Mantive a faixa de SDK, mas ajustei o formato.

# dependencies:
#   flutter:
#     sdk: flutter
  
#   # DEPENDÊNCIAS ADICIONADAS PARA A API E FORMATAÇÃO:
#   http: ^1.1.0 # Para requisições HTTP (API)
#   intl: ^0.19.0 # Para formatação de data e hora em diferentes idiomas (pt_BR)

#   cupertino_icons: ^1.0.8

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/moon_logo.png
#     - assets/stars_bg.jpg


name: morpheus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # fl_chart: ^0.69.0  <--- LINHA REMOVIDA PARA EVITAR O ERRO DE REDE

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/moon_logo.png
    - assets/stars_bg.jpg